
SELECT * FROM customer LIMIT 10;

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

SELECT customer_id , purchase_amount
FROM customer
WHERE discount_applied ='Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

SELECT item_purchased , round(AVG(review_rating::numeric),2) as Avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

SELECT shipping_type, ROUND(AVG(purchase_amount))
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

SELECT item_purchased, ROUND( 100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

SELECT * FROM customer LIMIT 10;
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

SELECT customer_segment,COUNT(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
)

SELECT *
FROM (
    SELECT 
        category,
        item_purchased,
        total_orders,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS rnk
    FROM item_counts
) x
WHERE rnk <= 3;

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


--problems that we solved :
--Q1. What is the total revenue generated by male vs. female customers?
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
-- Q3. Which are the top 5 products with the highest average review rating?
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
--Q8. What are the top 3 most purchased products within each category?
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group?




